/* ============================================================
   Home galleries — three auto-scrolling filmstrip rows
   (whare / whenua / tangata), HALF SPEED.

   Each folder is one horizontally scrolling strip (duplicated set
   for a seamless loop). Hover/focus pauses a strip. Clicking any
   photo opens the full-screen overlay album (js/lightbox.js).

   Speed: duration was doubled (max(120, n*14)s) = half the previous
   scroll speed. Tweak SCROLL_BASE/SCROLL_PER_ITEM to adjust.

   Performance:
   - PREVIEW_LIMIT caps how many thumbnails a strip shows inline;
     the lightbox still opens the FULL image set for that section.
   - A strip only builds (and requests) its thumbnails when it comes
     near the viewport (IntersectionObserver), so the home page no
     longer eagerly downloads ~100 gallery images at load.
   - IMG_VER cache-busts the WebP URLs so re-generated/rotated
     images are picked up without visitors hard-refreshing.

   Filenames from js/gallery-manifest.js (scripts/optimize-images.sh)
   with SITE_CONFIG.GALLERY_SECTIONS (js/config.js) as fallback.
   Thumbs: public/images/gallery-web/<folder>/thumbs/<file>
   Full:   public/images/gallery-web/<folder>/full/<file>
   Images are served as WebP (generated by scripts/optimize-images.sh)
   for modern browsers; the manifest already lists .webp names and the
   config fallback names are converted to .webp here.
   ============================================================ */
(function () {
  var root = document.getElementById("galleries-root");
  if (!root) return;

  var cfg = (typeof SITE_CONFIG !== "undefined") ? SITE_CONFIG : {};
  var manifest = window.GALLERY_MANIFEST || null;
  var SCROLL_BASE = 120;      /* seconds — half the earlier 60s */
  var SCROLL_PER_ITEM = 14;   /* seconds — half the earlier 7s  */
  var PREVIEW_LIMIT = 12;     /* thumbnails shown inline per strip */
  var IMG_VER = "2";          /* bump when gallery WebPs are re-generated */

  var reduced = window.matchMedia &&
    window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  var sections = (cfg.GALLERY_SECTIONS || [])
    .map(function (s) {
      var files = (manifest && manifest[s.folder]) ? manifest[s.folder] : (s.images || []);
      return {
        title: s.title || s.key,
        subtitle: s.subtitle || "",
        folder: s.folder || s.key,
        altPrefix: s.altPrefix || "Ahi o te Manawa photograph",
        images: files
      };
    })
    .filter(function (s) { return s.images && s.images.length; });

  /* every gallery image is generated as WebP (see optimize-images.sh),
     so normalise whatever filename we were given to its .webp sibling */
  function toWebp(name) {
    return String(name).replace(/\.[^./\\]+$/, ".webp");
  }
  function thumbUrl(sec, file) {
    return "public/images/gallery-web/" + sec.folder + "/thumbs/" + toWebp(file) + "?v=" + IMG_VER;
  }
  function fullUrl(sec, file) {
    return "public/images/gallery-web/" + sec.folder + "/full/" + toWebp(file) + "?v=" + IMG_VER;
  }

  function buildItem(sec, file, i, isDup) {
    var btn = document.createElement("button");
    btn.type = "button";
    btn.className = "gal-item" + (isDup ? " dup" : "");
    btn.setAttribute("aria-label",
      "View photo " + (i + 1) + " of " + sec.images.length + " — " + sec.title);

    var img = document.createElement("img");
    img.src = thumbUrl(sec, file);
    img.alt = sec.altPrefix + " (" + (i + 1) + ")";
    img.loading = "lazy";
    img.decoding = "async";
    img.addEventListener("error", function () { btn.remove(); });
    btn.appendChild(img);

    btn.addEventListener("click", function () {
      var items = sec.images.map(function (f, j) {
        return { src: fullUrl(sec, f), alt: sec.altPrefix + " (" + (j + 1) + ")" };
      });
      if (typeof window.openLightbox === "function") {
        window.openLightbox(items, i, sec.title);
      }
    });
    return btn;
  }

  sections.forEach(function (sec) {
    var block = document.createElement("div");
    block.className = "gal-block";

    var head = document.createElement("div");
    head.className = "gal-row-head";
    var h = document.createElement("h3");
    h.className = "gal-title";
    h.textContent = sec.title;
    head.appendChild(h);
    if (sec.subtitle) {
      var sub = document.createElement("span");
      sub.className = "gal-sub";
      sub.textContent = sec.subtitle;
      head.appendChild(sub);
    }
    block.appendChild(head);

    var strip = document.createElement("div");
    strip.className = "gal-strip";

    var track = document.createElement("div");
    track.className = "gal-track";

    /* preview set: first N images (original indices kept, so a preview
       click opens the lightbox on the same photo within the full set) */
    var previewFiles = sec.images.slice(0, PREVIEW_LIMIT);
    /* half speed: doubled durations */
    track.style.setProperty("--dur", Math.max(SCROLL_BASE, previewFiles.length * SCROLL_PER_ITEM) + "s");

    strip.appendChild(track);
    block.appendChild(strip);
    root.appendChild(block);

    /* defer building (and downloading) until the strip is near the
       viewport; falls back to immediate build for reduced-motion or
       browsers without IntersectionObserver */
    if (reduced || !("IntersectionObserver" in window)) {
      populate(track, sec, previewFiles);
    } else {
      var io = new IntersectionObserver(function (entries) {
        entries.forEach(function (entry) {
          if (entry.isIntersecting) {
            populate(track, sec, previewFiles);
            io.disconnect();
          }
        });
      }, { rootMargin: "400px 0px" });
      io.observe(strip);
    }
  });

  /* fill the (initially empty) track with the preview set + seamless dup */
  function populate(track, sec, previewFiles) {
    if (track.dataset.populated) return;
    track.dataset.populated = "1";
    previewFiles.forEach(function (file, i) {
      track.appendChild(buildItem(sec, file, i, false));
    });
    previewFiles.forEach(function (file, i) {
      track.appendChild(buildItem(sec, file, i, true));
    });
  }

  /* make sure every strip is animating immediately from page load
     (no hover needed) — force one reflow then confirm play state */
  requestAnimationFrame(function () {
    Array.prototype.forEach.call(
      document.querySelectorAll(".gal-track"),
      function (t) {
        void t.offsetWidth; /* reflow to kick the animation */
        t.style.animationPlayState = "running";
      }
    );
  });
})();